#letting make work for us...

CC=gcc
CFLAGS=-g -Wall -std=c11
LDFLAGS=
SOURCES := $(wildcard *.c)
PP=$(SOURCES:.c=.i)
ASM=$(SOURCES:.c=.s)
OBJECTS-INT=$(SOURCES:.c=-int.o)
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=hello

# ===========================================================

# The typical case. Preprocessing and compiling and assembling,
# then linking to make an executable. 

output: $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

$(OBJECTS): %.o : %.c
	$(CC) -c $(CFLAGS) $< -o $@
